require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/end_points", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EndPoint. As you add validations to EndPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EndPoint.create! valid_attributes
      get end_points_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      end_point = EndPoint.create! valid_attributes
      get end_point_url(end_point)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_end_point_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      end_point = EndPoint.create! valid_attributes
      get edit_end_point_url(end_point)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EndPoint" do
        expect {
          post end_points_url, params: { end_point: valid_attributes }
        }.to change(EndPoint, :count).by(1)
      end

      it "redirects to the created end_point" do
        post end_points_url, params: { end_point: valid_attributes }
        expect(response).to redirect_to(end_point_url(EndPoint.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EndPoint" do
        expect {
          post end_points_url, params: { end_point: invalid_attributes }
        }.to change(EndPoint, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post end_points_url, params: { end_point: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested end_point" do
        end_point = EndPoint.create! valid_attributes
        patch end_point_url(end_point), params: { end_point: new_attributes }
        end_point.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the end_point" do
        end_point = EndPoint.create! valid_attributes
        patch end_point_url(end_point), params: { end_point: new_attributes }
        end_point.reload
        expect(response).to redirect_to(end_point_url(end_point))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        end_point = EndPoint.create! valid_attributes
        patch end_point_url(end_point), params: { end_point: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested end_point" do
      end_point = EndPoint.create! valid_attributes
      expect {
        delete end_point_url(end_point)
      }.to change(EndPoint, :count).by(-1)
    end

    it "redirects to the end_points list" do
      end_point = EndPoint.create! valid_attributes
      delete end_point_url(end_point)
      expect(response).to redirect_to(end_points_url)
    end
  end
end
